### ISSUE TITLE
Zynaptik Switch doesn't work for Program Change

### ISSUE THREAD

**Issue by wyleu** [zynthian/zyncoder#32]
**Describe the bug**
Selecting program change in the wiring webconf does not work for Program Change . All the other do work

**To Reproduce**
1. Go to webconf wiring
2. Select Zynaptik awitch 5 for zynaptik i/o 
3. reboot
4. All other options produce expected behaviour , Program Change does not

**Expected behavior**
I expect to see a MIDI log message for program change when the button is pressed

**Screenshots**

![image](https://user-images.githubusercontent.com/79083/110157044-a4250280-7ddf-11eb-8b36-656284e48bf5.png)

**Comment by jofemodo** [comment]
As you can see, *ALL* program changes are intercepted by the zynthian UI and you can't see them on the ZynMidiRouter output.  

It was implemented like this because most of the standalone engines listen for PGs, what collides with the UI's bank/preset manager.

This should be improved because it's a limitation for some use-cases, specially when using pure MIDI layers. I will leave this issue open and will try to improve this behaviour:

Program Change messages should be deleted from the ZynMidiRouter output **only** when strictly needed for avoiding collision with UI. That is, only when the output goes to any of these engines:

+ ZynAddSubFX
+ FluidSynth
+ setBfree
+ Aeolus
+ Pianoteq

As ZynMidiRouter is engine-agnostic (It doesn't know about layers or engines), i have to implement a flag that can be enabled/disabled for each output port externally. I've to think a little bit about this ... ;-)

Regards,

**Comment by jofemodo** [comment]
Hi @wyleu !

I just committed a patch that solves partially the problem. The improved code *only* drop PC messages from "engine" output ports (Main & CH#XX), allowing the PCs to flow thru the rest of output ports (MIDI-OUT, NET, etc.).

If you select, for instance, "MIDI-OUT" on the MIDI-log selector, you should see the PCs generated by your switches (don't forget to update first ;-).

Regards,

**Comment by wyleu** [comment]
![image](https://user-images.githubusercontent.com/79083/111044735-437e7100-8442-11eb-972f-f5a1f19ccaee.png)

Ok that programmes the buttons as per https://wiki.zynthian.org/index.php/Zynthian_UI_Users_Guide#MIDI_Program_Change_.26_ZS3_.28SubSnapShots.29

Time to close :-D

**Comment by jofemodo** [comment]
Hi @wyleu !

I just committed a patch that solves completely the issue. Now "Program Change" messages are only blocked for the engines that really need it: Aeolus, FLuidSYnth, setBfree & ZynAddSubFX
